### ISSUE TITLE
segfault caused by "Smart Codec" feature enabled on IP cam

### ISSUE THREAD

**Issue by antonsviridenko** [bluecherrydvr/bluecherry-client#299]
```
[rtsp @ 0x7fff48002fa0] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options                                                                                                                                   
processing stream id  0 
trying to use VAAPI acceleration for video stream decoding 
RtspStream: stream # 0 : Video: h264, 1 reference frame, none(left) 
video stream index:  0 
audio steam index:  -1 
get_format() callback for AVCodecContext  0x7fff4800f220 
checking pix fmt  vaapi_vld         0          0 
Trying to initialize VAAPI decoder 
initializing VAAPI decoder... 
returning pix_fmt  vaapi_vld         0          0 
[h264 @ 0x7fff4800f220] Reinit context to 1920x1088, pix_fmt: vaapi_vld
Assertion desc failed at libswscale/swscale_internal.h:672

Thread 9 "QThread" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fff4e34d700 (LWP 4553)]
0x00007ffff09d6fa5 in raise () from /lib64/libc.so.6
(gdb) bt full
#0  0x00007ffff09d6fa5 in raise () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007ffff09d8c2a in abort () from /lib64/libc.so.6
No symbol table info available.
#2  0x00007ffff1d48f65 in isGray (pix_fmt=<optimized out>) at libswscale/swscale_internal.h:693
        desc = <optimized out>
#3  sws_setColorspaceDetails (c=c@entry=0x7fff48706ae0, inv_table=0x7ffff1d6a710 <ff_yuv2rgb_coeffs+80>, srcRange=0, table=0x7ffff1d6a710 <ff_yuv2rgb_coeffs+80>, dstRange=<optimized out>, 
    brightness=brightness@entry=0, contrast=65536, saturation=65536) at libswscale/utils.c:858
        desc_dst = <optimized out>
        desc_src = <optimized out>
        need_reinit = <optimized out>
#4  0x00007ffff1cff09a in sws_init_context (c=c@entry=0x7fff48706ae0, srcFilter=srcFilter@entry=0x0, dstFilter=dstFilter@entry=0x0) at libswscale/utils.c:1180
        i = <optimized out>
        usesVFilter = <optimized out>
        usesHFilter = <optimized out>
        unscaled = 1
        dummyFilter = {lumH = 0x0, lumV = 0x0, chrH = 0x0, chrV = 0x0}
        srcW = 1920
        srcH = 1080
        dstW = 1920
        dstH = 1080
        dst_stride = 3920
        flags = 1
        cpu_flags = 1037275
        srcFormat = AV_PIX_FMT_NONE
        dstFormat = AV_PIX_FMT_BGRA
        desc_src = <optimized out>
        desc_dst = <optimized out>
        ret = 0
        tmpFmt = <optimized out>
#5  0x00007ffff1d49385 in sws_getCachedContext (context=0x7fff48706ae0, srcW=1920, srcH=1080, srcFormat=AV_PIX_FMT_NONE, dstW=1920, dstH=1080, dstFormat=AV_PIX_FMT_BGRA, flags=1, srcFilter=0x0, dstFilter=0x0, 
    param=0x7ffff1d69cc0 <default_param>) at libswscale/utils.c:2385
        default_param = {123456, 123456}
        src_h_chr_pos = -513
        dst_h_chr_pos = -513
        src_v_chr_pos = -513
        dst_v_chr_pos = -513
#6  0x000000000049284f in RtspStreamFrameFormatter::updateSWSContext (this=this@entry=0x7fff480013d0, dstWidth=dstWidth@entry=1920, dstHeight=dstHeight@entry=1080)
    at /home/odsk/bluecherry-client/src/rtsp-stream/RtspStreamFrameFormatter.cpp:155
        pixFormat = <optimized out>
#7  0x00000000004928a7 in RtspStreamFrameFormatter::scaleFrame (this=this@entry=0x7fff480013d0, avFrame=avFrame@entry=0x7fff48059080, width=1920, height=1080)
    at /home/odsk/bluecherry-client/src/rtsp-stream/RtspStreamFrameFormatter.cpp:105
        bufSize = <optimized out>
        buf = <optimized out>
        result = <optimized out>
#8  0x00000000004929a5 in RtspStreamFrameFormatter::formatFrame (this=0x7fff480013d0, avFrame=avFrame@entry=0x7fff48059080, width=<optimized out>, height=<optimized out>)
    at /home/odsk/bluecherry-client/src/rtsp-stream/RtspStreamFrameFormatter.cpp:69
---Type <return> to continue, or q <return> to quit---
No locals.
#9  0x000000000049557b in RtspStreamWorker::processVideoFrame (this=this@entry=0x9f29f0, rawFrame=0x7fff48059080) at /home/odsk/bluecherry-client/src/rtsp-stream/RtspStreamWorker.cpp:277
No locals.
#10 0x000000000049567d in RtspStreamWorker::processPacket (this=this@entry=0x9f29f0, packet=...) at /home/odsk/bluecherry-client/src/rtsp-stream/RtspStreamWorker.cpp:185
        frame = <optimized out>
#11 0x0000000000495700 in RtspStreamWorker::processStream (this=this@entry=0x9f29f0) at /home/odsk/bluecherry-client/src/rtsp-stream/RtspStreamWorker.cpp:131
        ok = true
        packet = {buf = 0x7fff4802d3c0, pts = -9223372036854775808, dts = -9223372036854775808, data = 0x7fff480a7640 "", size = 50232, stream_index = 0, flags = 1, side_data = 0x0, side_data_elems = 0, 
          duration = 0, pos = -1, convergence_duration = 0}
        result = <optimized out>
#12 0x00000000004957e0 in RtspStreamWorker::processStreamLoop (this=this@entry=0x9f29f0) at /home/odsk/bluecherry-client/src/rtsp-stream/RtspStreamWorker.cpp:120
        abortFlag = false
#13 0x00000000004974b8 in RtspStreamWorker::run (this=0x9f29f0) at /home/odsk/bluecherry-client/src/rtsp-stream/RtspStreamWorker.cpp:108
No locals.
#14 0x00000000004fc76d in RtspStreamWorker::qt_static_metacall (_o=<optimized out>, _id=<optimized out>, _a=<optimized out>, _c=<optimized out>)
    at /home/odsk/bluecherry-client/build/src/rtsp-stream/moc_RtspStreamWorker.cxx:68
        _t = <optimized out>
#15 0x00007ffff334259c in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) () from /usr/lib64/qt4/libQtCore.so.4
No symbol table info available.
#16 0x00007ffff3220a38 in ?? () from /usr/lib64/qt4/libQtCore.so.4
No symbol table info available.
#17 0x00007ffff18dc927 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#18 0x00007ffff0a9a8af in clone () from /lib64/libc.so.6
No symbol table info available.
(gdb) 

```

**Comment by antonsviridenko** [comment]
duplicates #295

**Comment by antonsviridenko** [comment]
https://github.com/bluecherrydvr/bluecherry-client/commit/ea3146b8d395dd2bb2671a94b773c89a037681ca
